### ISSUE TITLE
Fail check on empty keys

### ISSUE THREAD

**Issue by Nielio** [jwbay/i18next-json-sync#19]
I have two scripts in my `package.json`for this package.
```
"i18n": "sync-i18n --files src/assets/i18n/*.json --primary de --languages en --space 2 --newkeysempty",
"check-i18n": "npm run i18n -- --check"
```
`i18n` adds new keys to all other languages.
`check-i18n` checks for missing keys.

`check-i18n` should check if all keys are translated. But it doesn't fail for empty keys inserted by `i18n`.
Only for missing ones.

**Comment by jwbay** [comment]
This is an interesting case. I don't think I'll support this, as it means the tool could fail in check mode immediately after it was run -- e.g. conflicting with itself.

If you're using the "new keys empty" flag, the intent is really that they land in source control that way for a translation team to work on.

Still, since the files are just JSON, you could probably check for this in CI by just scanning the folder content for `""`.
